name: S3 Deploy
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v2
        
        - name: Deploy to S3
          run: aws s3 sync / s3://{ secrets.S3_BUCKET_REGION }/ --delete --acl=public-read && aws cloudfront create-invalidation --distribution-id={ secrets.CLOUDFRONT_DISTRIBUTION_ID } --paths='/*'
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

